server:
  port: 8010
spring:
  application:
    name: MICROSERVICE-CONSUMER-MOVIE-RIBBON-CUSTOMIZING
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule